security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        WyndApi\WyndApiCoreBundle\Entity\ApiUser:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
        WyndApi\WyndApiCoreBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        user_db:
            entity:
                class: WyndApiWyndApiCoreBundle:ApiUser

    firewalls:
        api:
            pattern: ^/api/(?!token|swagger)
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - app.jwt_token_authenticator

    access_control:
        - { path: ^/api/token-authentication, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/swagger, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: [ROLE_USER, ROLE_ADMIN, ROLE_API_USER] }
