services:
    cache:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments: ['%kernel.cache_dir%']

    greenweez_import:
        class: ApiBundle\Service\GreenWeezImportFile
        arguments: ['%kernel.root_dir%', '@jms_serializer.serializer', '@api.product_manager', '@validator' ]